# Generated by Django 2.0.1 on 2018-11-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
