# Generated by Django 2.0.1 on 2018-11-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181121_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(help_text='Enter a Task (e.g. Create Project)', max_length=200)),
                ('points', models.IntegerField(help_text='Enter a Value between 1 to 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
