# Generated by Django 2.0.1 on 2018-11-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='I need to enter something here', help_text='Explain the task here (e.g. This task will help me do X, Y and Z)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(help_text='Enter your message here (e.g. Hello World, here I am!!)'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Enter a Title for the Note (e.g. ATTN Developers)', max_length=200),
        ),
    ]
