# Generated by Django 2.0.1 on 2018-11-23 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181121_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtype', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userid', models.CharField(blank=True, max_length=1000)),
                ('requestor', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=models.CharField(help_text='Enter a Task (e.g. Create Project)', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(help_text='Enter a Value between 1 to 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
