# Generated by Django 2.0.1 on 2018-11-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181124_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='requestor',
        ),
        migrations.AlterField(
            model_name='event',
            name='requestor',
            field=models.GenericIPAddressField(),
        ),
    ]
