# Generated by Django 2.0.1 on 2018-11-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_task_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_state',
            field=models.CharField(choices=[('unscheduled', 'unscheduled'), ('unstarted', 'unstarted'), ('started', 'started'), ('rejected', 'rejected'), ('finished', 'finished'), ('delivered', 'delivered'), ('accepted', 'accepted')], max_length=20),
        ),
    ]
