# Generated by Django 2.0.1 on 2018-11-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181127_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requestor',
            field=models.GenericIPAddressField(default='192.168.111.222'),
        ),
    ]
