# Generated by Django 2.0.1 on 2018-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_task_requestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requestor',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
