# Generated by Django 2.0.1 on 2018-11-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181129_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='requestor',
        ),
    ]
